'use client'

import { useState } from 'react'
import { ArrowDownRight, ArrowUpRight, BarChart3, CalendarDays, CircleAlert, CircleCheck, Download, FileSpreadsheet, Landmark, Menu, MoreHorizontal, ShieldCheck, TrendingUp, WalletCards, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const months = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul']
const monthlyData = [
  { month: 'Jan', revenue: 428173, net: 18102, operating: 36427 }, { month: 'Feb', revenue: 403626, net: 14124, operating: 29662 }, { month: 'Mar', revenue: 447287, net: 14275, operating: 38251 }, { month: 'Apr', revenue: 414266, net: 15126, operating: 38453 }, { month: 'Mei', revenue: 442152, net: 12110, operating: 33962 }, { month: 'Jun', revenue: 455475, net: 20481, operating: 42958 }, { month: 'Jul', revenue: 452742, net: 16822, operating: 44676 },
]
const profitSeries = months.map((month, i) => ({ month, rka: [19500, 19800, 20100, 20500, 21000, 21500, 22000][i], lastYear: [18097, 14098, 14260, 15122, 12102, 20470, 16818][i], actual: monthlyData[i].net, projection: i < 7 ? null : 18500 }))
const revenueBreakdown = [{ name: 'Tiket', actual: 1824000, rka: 1910000 }, { name: 'Subsidi', actual: 1032000, rka: 1100000 }, { name: 'Non-angkutan', actual: 187720, rka: 210000 }]
const spendBreakdown = [{ name: 'Belanja subsidi', actual: 2134000, rka: 2450000 }, { name: 'Belanja non-subsidi', actual: 782000, rka: 830000 }]
const formatM = (v: number) => `${Math.round(v).toLocaleString('id-ID')} jt`
const formatRp = (v: number) => `Rp ${Math.round(v).toLocaleString('id-ID')} jt`

function MetricCard({ label, value, change, note, positive = true, icon: Icon }: { label: string; value: string; change: string; note: string; positive?: boolean; icon: typeof WalletCards }) {
  return <article className="metric-card"><div className="metric-topline"><span className="metric-label">{label}</span><span className="metric-icon"><Icon size={17} /></span></div><div className="metric-value">{value}</div><div className="metric-foot"><span className={positive ? 'change positive' : 'change negative'}>{positive ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}{change}</span><span className="metric-note">{note}</span></div></article>
}
function ChartTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ name: string; value: number; color: string }>; label?: string }) { if (!active || !payload?.length) return null; return <div className="chart-tooltip"><strong>{label} 2026</strong>{payload.map((e) => <div key={e.name}><span style={{ background: e.color }} />{e.name}: {formatM(e.value)}</div>)}</div> }
function SeriesLegend({ items }: { items: Array<[string, string]> }) { return <div className="legend">{items.map(([label, color]) => <span key={label}><i style={{ background: color }} /> {label}</span>)}</div> }

export default function Page() {
  const [period, setPeriod] = useState('Januari – Juli 2026'); const [menuOpen, setMenuOpen] = useState(false); const [activeTab, setActiveTab] = useState('Ringkasan Keuangan')
  const tabs = [{ label: 'Ringkasan Keuangan', icon: BarChart3 }, { label: 'Laba & Rugi', icon: WalletCards }, { label: 'Posisi Keuangan', icon: Landmark }, { label: 'Proyeksi 2026', icon: TrendingUp }, { label: 'Kesehatan Keuangan', icon: ShieldCheck }]
  const totals = { revenue: 3043720.3, net: 111039.3 }; const projection = totals.net / 7 * 12; const margin = totals.net / totals.revenue * 100
  return <main className="dashboard-shell"><aside className={menuOpen ? 'sidebar open' : 'sidebar'}><div className="brand-lockup"><div className="brand-mark"><span /><span /><span /></div><div><strong>TRANSJAKARTA</strong><small>Finance Intelligence</small></div><button className="mobile-close" onClick={() => setMenuOpen(false)} aria-label="Tutup menu"><X size={18} /></button></div><div className="sidebar-section"><span className="section-kicker">OVERVIEW</span>{tabs.slice(0, 3).map(({ label, icon: Icon }) => <button key={label} className={activeTab === label ? 'nav-item active' : 'nav-item'} onClick={() => { setActiveTab(label); setMenuOpen(false) }}><Icon size={18} /> {label}</button>)}</div><div className="sidebar-section"><span className="section-kicker">INSIGHT</span>{tabs.slice(3).map(({ label, icon: Icon }) => <button key={label} className={activeTab === label ? 'nav-item active' : 'nav-item'} onClick={() => { setActiveTab(label); setMenuOpen(false) }}><Icon size={18} /> {label}</button>)}</div><div className="sidebar-bottom"><div className="data-status"><span className="status-dot" /><div><strong>Data tersinkron</strong><small>7 Agustus 2026, 09:42 WIB</small></div></div><div className="profile"><div className="avatar">FA</div><div><strong>Finance Analyst</strong><small>Unit Keuangan</small></div><MoreHorizontal size={18} /></div></div></aside><section className="content-area"><header className="topbar"><button className="mobile-menu" onClick={() => setMenuOpen(true)} aria-label="Buka menu"><Menu size={20} /></button><div className="breadcrumb"><span>Dashboard</span><span>/</span><strong>{activeTab}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Unduh laporan"><Download size={18} /></button><div className="top-avatar">FA</div></div></header><div className="content-wrap"><div className="page-heading"><div><p className="eyebrow">LAPORAN MANAJEMEN · 2026</p><h1>{activeTab}</h1><p className="subtitle">Pantau performa dan arah keuangan Transjakarta secara menyeluruh.</p></div><div className="period-control"><CalendarDays size={16} /><select value={period} onChange={(e) => setPeriod(e.target.value)} aria-label="Pilih periode"><option>Januari – Juli 2026</option><option>Januari – Juni 2026</option><option>Juli 2026</option></select></div></div><div className="data-notice"><FileSpreadsheet size={18} /><span><strong>Sumber data:</strong> BS-PL Transjakarta Januari–Juli 2026 · Angka dalam jutaan rupiah · RKA 2026 digunakan sebagai target.</span><button>Detail sumber <ArrowUpRight size={14} /></button></div>{activeTab === 'Ringkasan Keuangan' && <Summary totals={totals} projection={projection} margin={margin} />}{activeTab === 'Laba & Rugi' && <ProfitLoss />}{activeTab === 'Posisi Keuangan' && <Position />}{activeTab === 'Proyeksi 2026' && <Projection />}{activeTab === 'Kesehatan Keuangan' && <Health />}</div></section></main>
}

function Summary({ totals, projection, margin }: { totals: { revenue: number; net: number }; projection: number; margin: number }) { return <><div className="metric-grid"><MetricCard label="Laba bersih YTD" value={formatRp(totals.net)} change="−18,4%" positive={false} note="vs. RKA YTD Juli · YoY +0,03%" icon={WalletCards} /><MetricCard label="Proyeksi laba bersih" value={formatRp(projection)} change="Run-rate 12 bulan" note="berdasarkan rata-rata aktual" icon={TrendingUp} /><MetricCard label="Margin laba bersih" value={`${margin.toFixed(1).replace('.', ',')}%`} change="+1,8 pp" note="vs. target RKAP" icon={BarChart3} /><MetricCard label="Status kesehatan" value="Sehat" change="Stabil" note="pada 3 dari 4 indikator" icon={ShieldCheck} /></div><div className="main-grid"><section className="panel trend-panel"><div className="panel-heading"><div><p className="panel-kicker">PERFORMA BULANAN</p><h2>Pendapatan & laba bersih</h2></div><SeriesLegend items={[["Pendapatan operasi", 'var(--chart-1)'], ["Laba bersih", 'var(--chart-3)']]} /></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={300}><LineChart data={monthlyData}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="month" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} tickFormatter={(v) => `${v / 1000}M`} /><Tooltip content={<ChartTooltip />} /><Line dataKey="revenue" name="Pendapatan" stroke="var(--chart-1)" strokeWidth={3} /><Line dataKey="net" name="Laba bersih" stroke="var(--chart-3)" strokeWidth={2.5} /></LineChart></ResponsiveContainer></div><div className="chart-footnote">Juni menggunakan data aktual dari workbook BS-PL Juni 2026.</div></section><Health /></div><RevenueSpend /></> }
function ProfitLoss() { return <><section className="panel"><div className="panel-heading"><div><p className="panel-kicker">PERBANDINGAN LABA BERSIH</p><h2>Realisasi vs RKA dan periode tahun lalu</h2></div><SeriesLegend items={[["RKA 2026", 'var(--chart-2)'], ["2025", 'var(--chart-4)'], ["Realisasi", 'var(--chart-1)'], ["Proyeksi", 'var(--chart-3)']]} /></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={350}><LineChart data={profitSeries}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis tickFormatter={(v) => `${v / 1000}M`} /><Tooltip content={<ChartTooltip />} /><Line dataKey="rka" name="RKA 2026" stroke="var(--chart-2)" strokeDasharray="5 5" /><Line dataKey="lastYear" name="2025" stroke="var(--chart-4)" /><Line dataKey="actual" name="Realisasi" stroke="var(--chart-1)" strokeWidth={3} /><Line dataKey="projection" name="Proyeksi" stroke="var(--chart-3)" strokeDasharray="3 3" /></LineChart></ResponsiveContainer></div></section><RevenueSpend /></> }
function RevenueSpend() { return <div className="lower-grid"><section className="panel"><div className="panel-heading"><div><p className="panel-kicker">PENDAPATAN YTD</p><h2>Breakdown pendapatan</h2></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={260}><BarChart data={revenueBreakdown}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis tickFormatter={(v) => `${v / 1000}M`} /><Tooltip content={<ChartTooltip />} /><Bar dataKey="rka" name="RKA" fill="var(--chart-2)" /><Bar dataKey="actual" name="Realisasi" fill="var(--chart-1)" /></BarChart></ResponsiveContainer></div><p className="chart-footnote">Tiket dan subsidi merupakan pendapatan angkutan; non-angkutan ditampilkan terpisah.</p></section><section className="panel"><div className="panel-heading"><div><p className="panel-kicker">BELANJA YTD</p><h2>Subsidi vs non-subsidi</h2></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={260}><BarChart data={spendBreakdown}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis tickFormatter={(v) => `${v / 1000}M`} /><Tooltip content={<ChartTooltip />} /><Bar dataKey="rka" name="RKA" fill="var(--chart-2)" /><Bar dataKey="actual" name="Realisasi" fill="var(--chart-3)" /></BarChart></ResponsiveContainer></div></section></div> }
function Projection() { return <><div className="metric-grid"><MetricCard label="Proyeksi non-angkutan" value="Rp 342.000 jt" change="Target akhir tahun" note="berdasarkan outlook 2026" icon={TrendingUp} /><MetricCard label="Proyeksi laba bersih" value={formatRp(190353)} change="Run-rate" note="dari aktual Januari–Juli" icon={WalletCards} /><MetricCard label="Penyerapan belanja subsidi" value="87,1%" change="−12,9 pp" positive={false} note="terhadap RKA YTD Juli" icon={BarChart3} /><MetricCard label="Target penyerapan" value="100%" change="RKA 2026" note="batas kinerja akhir tahun" icon={ShieldCheck} /></div><RevenueSpend /><section className="panel"><div className="panel-heading"><div><p className="panel-kicker">OUTLOOK NON-ANGKUTAN</p><h2>Jalur menuju Rp342 miliar</h2></div></div><div className="projection-callout"><strong>Rp 342.000 juta</strong><span>proyeksi non-angkutan akhir tahun 2026</span></div></section></> }
function Position() { return <><div className="metric-grid"><MetricCard label="Aset" value="Rp 9.842.610 jt" change="+4,2%" note="vs. tahun lalu" icon={Landmark} /><MetricCard label="Liabilitas" value="Rp 4.216.830 jt" change="+1,1%" note="terkendali" icon={BarChart3} /><MetricCard label="Ekuitas" value="Rp 5.625.780 jt" change="+6,8%" note="menguat" icon={WalletCards} /><MetricCard label="Rasio liabilitas" value="42,8%" change="−1,3 pp" positive={false} note="lebih sehat dari 2025" icon={ShieldCheck} /></div><section className="panel"><div className="panel-heading"><div><p className="panel-kicker">POSISI KEUANGAN</p><h2>Ringkasan neraca per Juli 2026</h2></div></div><div className="table-wrap"><table><thead><tr><th>Komponen</th><th>Juli 2026</th><th>Perubahan</th><th>Status</th></tr></thead><tbody>{[['Aset', '9.842.610 jt', '+4,2%', 'Sehat'], ['Liabilitas', '4.216.830 jt', '+1,1%', 'Terkendali'], ['Ekuitas', '5.625.780 jt', '+6,8%', 'Menguat']].map((r) => <tr key={r[0]}>{r.map((v) => <td key={v}>{v}</td>)}</tr>)}</tbody></table></div></section></> }
function Health() { return <section className="panel health-panel"><div className="panel-heading"><div><p className="panel-kicker">FINANCIAL PULSE</p><h2>Indikator kesehatan keuangan</h2></div><CircleCheck className="health-check" size={21} /></div><div className="health-score"><div className="score-ring"><strong>78</strong><span>/ 100</span></div><div><strong className="score-title">Kondisi baik</strong><p>Keuangan berada pada jalur sehat dengan ruang perbaikan pada efisiensi beban.</p></div></div><div className="health-list"><div><span>Profitabilitas</span><strong>Baik</strong><i className="bar"><em style={{ width: '86%' }} /></i></div><div><span>Likuiditas</span><strong>Baik</strong><i className="bar"><em style={{ width: '78%' }} /></i></div><div><span>Efisiensi beban</span><strong>Perlu perhatian</strong><i className="bar warning"><em style={{ width: '59%' }} /></i></div></div></section> }
